version: "3"

tasks:
  process:all:
    desc: Run all data pipelines then all analysis
    cmds:
      - task: fetch:all
      - task: analyze:all

  fetch:all:
    desc: Run all data fetchers
    cmds:
      - task: fetch:imura
      - task: fetch:oracle
      - task: fetch:credit
      - task: fetch:etf
      - task: fetch:loan
      - task: fetch:metals
      - task: fetch:portfolio
      - task: fetch:yield

  analyze:all:
    desc: Run all analysis
    aliases: [run]
    cmds:
      - task: sync
      - task: lint
      - task: format
      - task: analyze:imura
      - task: analyze:oracle
      - task: analyze:credit
      - task: analyze:etf
      - task: analyze:loan
      - task: analyze:metals
      - task: analyze:portfolio
      - task: analyze:yield

  lint:
    cmd: uv run ruff check . --fix
  format:
    cmd: uv run ruff format .
  test:
    cmd: uv run pytest
  sync:
    cmd: uv sync

  fetch:imura:
    cmd: uv run python crew/imura/data_pipeline.py
  analyze:imura:
    cmd: uv run python crew/imura/analysis.py

  fetch:oracle:
    cmd: uv run python crew/oracle/data_pipeline.py
  analyze:oracle:
    cmd: uv run python crew/oracle/analysis.py

  fetch:credit:
    cmd: uv run python crew/credit/data_pipeline.py
  analyze:credit:
    cmd: uv run python crew/credit/analysis.py

  fetch:etf:
    cmd: uv run python crew/etf/data_pipeline.py
  analyze:etf:
    cmd: uv run python crew/etf/analysis.py

  fetch:loan:
    cmd: uv run python crew/loan/data_pipeline.py
  analyze:loan:
    cmd: uv run python crew/loan/analysis.py

  fetch:metals:
    cmd: uv run python crew/metals/data_pipeline.py
  analyze:metals:
    cmd: uv run python crew/metals/analysis.py

  fetch:portfolio:
    cmd: uv run python crew/portfolio/data_pipeline.py
  analyze:portfolio:
    cmd: uv run python crew/portfolio/analysis.py

  fetch:yield:
    cmd: uv run python crew/yields/data_pipeline.py
  analyze:yield:
    cmd: uv run python crew/yields/analysis.py
