version: "3"

tasks:
  process:all:
    desc: Run all data pipelines then all analysis
    cmds:
      - task: fetch:all
      - task: analyze:all

  fetch:all:
    desc: Run all data fetchers
    cmds:
      - task: fetch:imura
      - task: fetch:oracle
      - task: fetch:credit
      - task: fetch:etf
      - task: fetch:loan
      - task: fetch:metals
      - task: fetch:portfolio
      - task: fetch:yield
      - task: fetch:semiconductors
      - task: fetch:legendary_investors

  analyze:all:
    desc: Run all analysis
    aliases: [run]
    cmds:
      - task: sync
      - task: lint
      - task: format
      - task: analyze:imura
      - task: analyze:oracle
      - task: analyze:credit
      - task: analyze:etf
      - task: analyze:loan
      - task: analyze:metals
      - task: analyze:portfolio
      - task: analyze:yield
      - task: analyze:semiconductors
      - task: analyze:legendary_investors

  lint:
    cmd: uv run ruff check . --fix
  format:
    cmd: uv run ruff format .
  sync:
    cmd: uv sync

  fetch:imura:
    cmd: uv run python -m crew.imura.data_pipeline
  analyze:imura:
    cmd: uv run python -m crew.imura.analysis

  fetch:oracle:
    cmd: uv run python -m crew.oracle.data_pipeline
  analyze:oracle:
    cmd: uv run python -m crew.oracle.analysis

  fetch:credit:
    cmd: uv run python -m crew.credit.data_pipeline
  analyze:credit:
    cmd: uv run python -m crew.credit.analysis

  fetch:etf:
    cmd: uv run python -m crew.etf.data_pipeline
  analyze:etf:
    cmd: uv run python -m crew.etf.analysis

  fetch:loan:
    cmd: uv run python -m crew.loan.data_pipeline
  analyze:loan:
    cmd: uv run python -m crew.loan.analysis

  fetch:metals:
    cmd: uv run python -m crew.metals.data_pipeline
  analyze:metals:
    cmd: uv run python -m crew.metals.analysis

  fetch:portfolio:
    cmd: uv run python -m crew.portfolio.data_pipeline
  analyze:portfolio:
    cmd: uv run python -m crew.portfolio.analysis

  fetch:yield:
    cmd: uv run python -m crew.yields.data_pipeline
  analyze:yield:
    cmd: uv run python -m crew.yields.analysis

  fetch:semiconductors:
    cmd: uv run python -m crew.semiconductors.data_pipeline
  analyze:semiconductors:
    cmd: uv run python -m crew.use_case_runner semiconductors --config config/use_cases/semiconductors.yaml

  fetch:legendary_investors:
    cmd: uv run python -m crew.legendary_investors.data_pipeline
  analyze:legendary_investors:
    cmd: uv run python -m crew.use_case_runner legendary_investors --config config/use_cases/legendary_investors.yaml

  serve:
    desc: Run the HTMX web dashboard
    cmd: uv run python web/app.py
