#!/usr/bin/env python3
import os
import sys
from pathlib import Path

# 翻訳対象ファイルリスト
files = [
    "freqtrade/docs/bot-usage.md",
    "freqtrade/docs/bot-basics.md",
    "freqtrade/docs/backtesting.md",
    "freqtrade/docs/commands/list-timeframes.md",
    "freqtrade/docs/commands/list-strategies.md",
    "freqtrade/docs/commands/list-pairs.md",
    "freqtrade/docs/commands/list-markets.md",
    "freqtrade/docs/commands/list-hyperoptloss.md",
    "freqtrade/docs/commands/list-freqaimodels.md",
    "freqtrade/docs/commands/list-exchanges.md",
    "freqtrade/docs/commands/list-data.md",
    "freqtrade/docs/commands/install-ui.md",
    "freqtrade/docs/commands/hyperopt.md",
    "freqtrade/docs/commands/hyperopt-show.md",
    "freqtrade/docs/commands/hyperopt-list.md",
    "freqtrade/docs/commands/edge.md",
    "freqtrade/docs/commands/download-data.md",
    "freqtrade/docs/commands/create-userdir.md",
    "freqtrade/docs/commands/convert-trade-data.md",
    "freqtrade/docs/commands/convert-db.md",
    "freqtrade/docs/commands/convert-data.md",
    "freqtrade/docs/commands/backtesting.md",
    "freqtrade/docs/commands/backtesting-show.md",
    "freqtrade/docs/commands/backtesting-analysis.md",
    "freqtrade/docs/strategy-callbacks.md",
    "freqtrade/docs/strategy-advanced.md",
    "freqtrade/docs/strategy-101.md",
    "freqtrade/docs/stoploss.md",
    "freqtrade/docs/sql_cheatsheet.md",
    "freqtrade/docs/rest-api.md",
    "freqtrade/docs/recursive-analysis.md",
    "freqtrade/docs/producer-consumer.md",
    "freqtrade/docs/plugins.md",
    "freqtrade/docs/plotting.md",
    "freqtrade/docs/lookahead-analysis.md",
    "freqtrade/docs/leverage.md",
    "freqtrade/docs/installation.md",
    "freqtrade/docs/index.md",
    "freqtrade/docs/hyperopt.md",
    "freqtrade/docs/freqai.md",
    "freqtrade/docs/freqai-running.md",
    "freqtrade/docs/freqai-reinforcement-learning.md",
    "freqtrade/docs/freqai-parameter-table.md",
    "freqtrade/docs/freqai-feature-engineering.md",
    "freqtrade/docs/freqai-developers.md",
    "freqtrade/docs/freqai-configuration.md",
    "freqtrade/docs/freq-ui.md",
    "freqtrade/docs/faq.md",
    "freqtrade/docs/exchanges.md",
    "freqtrade/docs/docker_quickstart.md",
    "freqtrade/docs/developer.md",
    "freqtrade/docs/deprecated.md",
    "freqtrade/docs/data-download.md",
    "freqtrade/docs/data-analysis.md",
    "freqtrade/docs/configuration.md",
    "freqtrade/docs/includes/strategy-imports.md",
    "freqtrade/docs/includes/strategy-exit-comparisons.md",
    "freqtrade/docs/includes/showcase.md",
    "freqtrade/docs/includes/release_template.md",
    "freqtrade/docs/includes/protections.md",
    "freqtrade/docs/includes/pricing.md",
    "freqtrade/docs/includes/pairlists.md",
    "freqtrade/docs/includes/exchange-features.md",
    "freqtrade/docs/includes/cors.md",
    "freqtrade/docs/commands/webserver.md",
    "freqtrade/docs/commands/trades-to-ohlcv.md",
    "freqtrade/docs/commands/trade.md",
    "freqtrade/docs/commands/test-pairlist.md",
    "freqtrade/docs/commands/strategy-updater.md",
    "freqtrade/docs/commands/show-trades.md",
    "freqtrade/docs/commands/show-config.md",
    "freqtrade/docs/commands/recursive-analysis.md",
    "freqtrade/docs/commands/plot-profit.md",
    "freqtrade/docs/commands/plot-dataframe.md",
    "freqtrade/docs/commands/new-strategy.md",
    "freqtrade/docs/commands/new-config.md",
    "freqtrade/docs/commands/main.md",
    "freqtrade/docs/commands/lookahead-analysis.md",
    "freqtrade/docs/strategy_migration.md",
    "freqtrade/docs/strategy_analysis_example.md",
    "freqtrade/docs/strategy-customization.md",
    "freqtrade/docs/windows_installation.md",
    "freqtrade/docs/webhook-config.md",
    "freqtrade/docs/utils.md",
    "freqtrade/docs/updating.md",
    "freqtrade/docs/trade-object.md",
]

base_dir = Path("/home/kafka/projects/crewTrade")

print(f"翻訳対象: {len(files)}ファイル")
print("処理開始...")

for i, file_path in enumerate(files, 1):
    full_path = base_dir / file_path
    print(f"[{i}/{len(files)}] {file_path}")

sys.exit(0)
