name: securities_collateral_loan
period: 3y
loan_amount: 10000000
annual_interest_rate: 0.01875
ltv_limit: 0.6
warning_ratio: 0.7
liquidation_ratio: 0.85
collateral_assets:
  - ticker: 1306.T
    quantity: 73
    description: NEXT FUNDS TOPIX ETF
  - ticker: 2568.T
    quantity: 118
    description: NASDAQ100 ETF (No Hedge)
  - ticker: 2510.T
    quantity: 19302
    description: NEXT FUNDS Domestic Bond NOMURA-BPI
  - ticker: 2622.T
    quantity: 159
    description: iShares USD Emerging Markets Bond Hedged
  - ticker: 348A.T
    quantity: 1004
    description: MAXIS Yomiuri 333 ETF
scenarios:
  - drop_pct: 0.1
    label: "-10%"
  - drop_pct: 0.2
    label: "-20%"
  - drop_pct: 0.3
    label: "-30%"
  - drop_pct: 0.4
    label: "-40%"
interest_horizons_days:
  - 30
  - 90
  - 180
optimization:
  enabled: true
  objective_weights:
    sharpe: 0.6
    volatility: 0.4
  constraints:
    min_weight: 0.05
    max_weight: 0.35
    max_category_weight: 0.5
    max_volatility: 0.12
  sample_size: 20000
  lookback: 3y
  profiles:
    - name: max_sharpe
      objective_weights:
        sharpe: 1.0
        volatility: 0.0
      correlation_threshold: 0.92
      max_portfolio_size: 14
      min_assets: 6
    - name: low_volatility
      objective_weights:
        sharpe: 0.2
        volatility: 0.8
      correlation_threshold: 0.85
      max_portfolio_size: 8
      min_assets: 5
      constraints_override:
        max_weight: 0.28
        min_weight: 0.04
    - name: cost_focus
      objective_weights:
        sharpe: 0.5
        volatility: 0.2
        expense: 0.3
      correlation_threshold: 0.9
      max_portfolio_size: 10
      min_assets: 6
      constraints_override:
        max_weight: 0.22
        min_weight: 0.03
